version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: festivals_app
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"  # Only expose locally since Nginx will proxy
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=festivals_user
      - DB_PASSWORD=festivals_password
      - DB_NAME=festivals_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: festivals_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: festivals_user
      POSTGRES_PASSWORD: festivals_password
      POSTGRES_DB: festivals_db
    ports:
      - "127.0.0.1:5432:5432"  # Only expose locally for security
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U festivals_user -d festivals_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
