version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "127.0.0.1:3000:80"
    environment:
      - REACT_APP_API_URL=${API_URL:-http://localhost:3001}
    dnepends_on:
      - server
    networks:
      - app_network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "${SERVER_PORT:-3001}:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${SERVER_PORT:-3001}
      - DB_HOST=db
      - DB_USER=${DB_USER:-festivals_user}
      - DB_PASSWORD=${DB_PASSWORD:-festivals_password}
      - DB_NAME=${DB_NAME:-festivals_db}
      - DB_PORT=${DB_PORT:-5432}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin_password}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    container_name: festivals_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-festivals_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-festivals_password}
      POSTGRES_DB: ${DB_NAME:-festivals_db}
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-dev.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-festivals_user} -d ${DB_NAME:-festivals_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
